# Generated by Django 4.2.30 on 2026-09-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='学期内递增的版本号，从 1 开始')),
                ('status', models.CharField(choices=[('published', '已发布')], default='published', max_length=20)),
                ('content_hash', models.CharField(help_text='发布时刻课表内容的指纹，用于识别重复发布', max_length=64)),
                ('entry_count', models.PositiveIntegerField(default=0, help_text='快照条目数量')),
                ('comment', models.CharField(blank=True, help_text='发布备注', max_length=255)),
                ('published_by', models.CharField(blank=True, help_text='发布操作人', max_length=150)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_versions', to='core.semester')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSnapshotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entry_id', models.PositiveIntegerField(blank=True, help_text='来源 ScheduleEntry 的 id（仅作追溯，不做外键约束）', null=True)),
                ('class_id', models.PositiveIntegerField()),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('course_id', models.PositiveIntegerField()),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('teacher_id', models.PositiveIntegerField()),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('classroom_id', models.PositiveIntegerField()),
                ('classroom_name', models.CharField(blank=True, max_length=100)),
                ('day_of_week', models.IntegerField(help_text='1-5 代表周一到周五')),
                ('period', models.IntegerField(help_text='第几节课')),
                ('is_locked', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_entries', to='core.semester')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='publication.scheduleversion')),
            ],
            options={
                'ordering': ['day_of_week', 'period', 'class_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(fields=('semester', 'version_number'), name='unique_version_number_per_semester'),
        ),
        migrations.AddIndex(
            model_name='schedulesnapshotentry',
            index=models.Index(fields=['version', 'day_of_week', 'period'], name='publication_version_5c18ac_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesnapshotentry',
            index=models.Index(fields=['semester', 'class_id'], name='publication_semeste_665b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesnapshotentry',
            index=models.Index(fields=['semester', 'teacher_id'], name='publication_semeste_d5cc82_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulesnapshotentry',
            index=models.Index(fields=['semester', 'classroom_id'], name='publication_semeste_399bd7_idx'),
        ),
    ]
