# Generated by Django 4.2.30 on 2026-09-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='1-5 代表周一到周五')),
                ('period', models.IntegerField(help_text='第几节课')),
                ('is_locked', models.BooleanField(default=False, help_text='锁定后不参与自动重排')),
                ('is_conflict', models.BooleanField(default=False)),
                ('conflict_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.class')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('original_teacher', models.ForeignKey(blank=True, help_text='如果是代课，记录原教师', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_for', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'day_of_week', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_source', to='scheduling.scheduleentry')),
                ('entry2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_target', to='scheduling.scheduleentry')),
                ('requesting_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('target_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_record', to='scheduling.scheduleentry')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='学期内递增的发布版本号')),
                ('snapshot', models.JSONField(help_text='发布时刻全部课表条目的快照')),
                ('entry_count', models.PositiveIntegerField(default=0, help_text='快照内条目数')),
                ('content_hash', models.CharField(help_text='快照内容指纹，用于识别重复发布', max_length=64)),
                ('published_by', models.CharField(blank=True, help_text='发布人', max_length=150)),
                ('note', models.CharField(blank=True, help_text='发布备注', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_versions', to='core.semester')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePublishLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now=True)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_lock', to='core.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('teacher', '教师冲突'), ('classroom', '教室冲突'), ('class', '班级冲突')], max_length=20)),
                ('day_of_week', models.IntegerField()),
                ('period', models.IntegerField()),
                ('involved_entries', models.JSONField(default=list)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='core.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'ordering': ['semester', 'class_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(fields=('semester', 'version_number'), name='unique_version_number_per_semester'),
        ),
        migrations.AlterUniqueTogether(
            name='classcourse',
            unique_together={('class_id', 'course', 'teacher', 'semester')},
        ),
    ]
